### PR TITLE
Fix fullscreen hover text

### LINKED ISSUE #203: Wrong hover-over text of the fullscreen icon in fullscreen mode
Steps to reproduce:
1. Open an AppRTC call  https://apprtc.appspot.com/r/00113176?debug=loopback
2. Click on the fullscreen icon to "Enter fullscreen"
3. Once in fullscreen mode, hover over the same icon and notice the text that shows up

Actual result:
Hover over the fullscreen icon in fullscreen mode, shows the text "Enter fullscreen"

Expected result:
Hover over the fullscreen icon in fullscreen mode, should display the text "Exit fullscreen" instead of Enter

### PR DESCRIPTION
**Pull request by KaptenJansson**
Fixes #203

### CODE REVIEW

File: src/web_app/js/appcontroller.js [hunk 1]
```diff
@@ -454,9 +454,13 @@ AppController.prototype.toggleVideoMute_ = function() {
 AppController.prototype.toggleFullScreen_ = function() {
   if (isFullScreen()) {
     trace('Exiting fullscreen.');
+    document.querySelector('#fullscreen').childNodes[1].innerHTML =
+        '<title>Enter fullscreen</title>';
```
Comment (samdutton) [inline src/web_app/js/appcontroller.js]: Could be simpler like this:

    document.querySelector('svg#fullscreen title').textContent = 'foo';

**Comment by samdutton** [comment]
Good catch! 

LGTM % nit

**Comment by KaptenJansson** [comment]
Yes that is a lot prettier ;). Thanks!
